require('./jquery-3.4.1.min');
require('./jquery.magnific-popup.min')
require('./bootstrap');
require('./custom');
require('./owl.carousel.min');
require('./popper.min');
require('./rtl');
require('./select2.min');
require('./slick.min');
require('./slick-animation.min');
